# Generated by Django 5.0.3 on 2024-03-18 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GCT01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_abonnement', models.DateTimeField()),
                ('date_fin_abonnement', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GCT02',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_action', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT07',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT08',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_sociale', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GCT09',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_compte_comptable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_diplome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_diplome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GCT16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employe', models.CharField(max_length=100)),
                ('prenom_employe', models.CharField(max_length=200)),
                ('date_naissance', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=15)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GCT17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_entreprise', models.CharField(max_length=100)),
                ('siege_sociale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_etablissement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_groupe_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_loisirs', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_piece_identite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_poste', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_profession', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT35',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_entretien', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT37',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_situation_matrimoniale', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT38',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_specialite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT39',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule_test_psycho', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_traitement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT41',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_type_contrat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utlisateur', models.CharField(max_length=200)),
                ('prenom_utilisateur', models.CharField(max_length=200)),
                ('date_naissance_user', models.CharField(max_length=15)),
                ('adresse_user', models.CharField(max_length=15)),
                ('telephone_user', models.CharField(max_length=15)),
                ('email_user', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GCT43',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_type_question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT45',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_niveau_access', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT46',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_entretien', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT51',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_type_question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT52',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_type_test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT54',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_type_utilisateur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GCT55',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_competences', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('text', 'Texte'), ('audio', 'Audio'), ('image', 'Image')], default='text', max_length=5)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GCT12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct13')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct18')),
            ],
        ),
        migrations.CreateModel(
            name='GCT25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct07')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct13')),
            ],
        ),
        migrations.CreateModel(
            name='GCT26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct07')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct32')),
            ],
        ),
        migrations.CreateModel(
            name='GCT33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct07')),
                ('loisir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct24')),
            ],
        ),
        migrations.CreateModel(
            name='GCT04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct07')),
                ('situation_matrimoniale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct37')),
            ],
        ),
        migrations.CreateModel(
            name='GCT05',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct07')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct38')),
            ],
        ),
        migrations.CreateModel(
            name='GCT15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct07')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct39')),
            ],
        ),
        migrations.CreateModel(
            name='GCT19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct17')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct32')),
                ('type_contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct41')),
            ],
        ),
        migrations.CreateModel(
            name='GCT10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('traitement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct40')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct42')),
            ],
        ),
        migrations.CreateModel(
            name='GCT03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_appel_offre', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('ageLimite', models.CharField(max_length=10)),
                ('missionPrincipale', models.CharField(max_length=100)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct38')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct42')),
            ],
        ),
        migrations.CreateModel(
            name='GCT44',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct07')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct17')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct18')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct19')),
                ('loisir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct24')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gct34')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.question')),
            ],
        ),
    ]
